name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Run lint checks
      run: ./gradlew lintDebug
      continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up signing config
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
    - name: Build and sign release APK
      run: ./gradlew assembleRelease
      env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Build and sign release AAB
      run: ./gradlew bundleRelease
      env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: Build debug AAB
      run: ./gradlew bundleDebug

    - name: Rename APKs and AABs with version
      run: |
        VERSION="1.0+${{ github.run_number }}"
        cp app/build/outputs/apk/debug/app-debug.apk "PlayaPhotobooth-debug-${VERSION}.apk"
        cp app/build/outputs/apk/release/app-release.apk "PlayaPhotobooth-release-${VERSION}.apk"
        cp app/build/outputs/bundle/debug/app-debug.aab "PlayaPhotobooth-debug-${VERSION}.aab"
        cp app/build/outputs/bundle/release/app-release.aab "PlayaPhotobooth-release-${VERSION}.aab"

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: PlayaPhotobooth-debug-*.apk

    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: PlayaPhotobooth-release-*.apk

    - name: Upload debug AAB
      uses: actions/upload-artifact@v4
      with:
        name: debug-aab
        path: PlayaPhotobooth-debug-*.aab

    - name: Upload release AAB
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: PlayaPhotobooth-release-*.aab

